// Config-driven node definitions
// This is the source of truth for all eight nodes.
// Adding a node here automatically creates a card on the dashboard.

const NODES = [
  {
    id: 'n1',
    name: 'Gulf Production & Bypass',
    category: 'physical',
    summary: 'Bypass pipeline utilisation vs capacity, Fujairah/Yanbu split',
    keyMetric: 'Bypass utilisation as % of capacity',
    phase: 2,
    manualSources: [
      'straits.live /status → pipelineBypass — automated (Petroline, ADCOP, Goreh-Jask)',
      'IEA Oil Market Report (monthly, paywalled) — detailed bypass analysis',
      'Kpler blog — Gulf export volumes (free, monthly recap)',
      'Windward AI / Vortexa — Fujairah vs Yanbu loading split',
    ],
    thresholdInfo: [
      'RED: Petroline ≥98% AND ADCOP at 100% (no spare bypass capacity)',
      'AMBER: Petroline ≥90%',
      'Fallback: manual bypass >5.0M bbl/d = red, >4.7M = amber',
    ],
    series: [
      { key: 'petroline_pct', label: 'Petroline utilisation (5M bpd)', unit: '%', manual: false, cadence: 'weekly', source: 'straits.live' },
      { key: 'adcop_pct', label: 'ADCOP utilisation (1.5M bpd)', unit: '%', manual: false, cadence: 'weekly', source: 'straits.live' },
      { key: 'bypass_utilisation', label: 'Bypass utilisation (manual)', unit: 'M bbl/d', manual: true, cadence: 'monthly' },
      { key: 'gulf_exports', label: 'Gulf crude exports', unit: 'M bbl/d', manual: true, cadence: 'monthly' },
      { key: 'fujairah_yanbu_split', label: 'Fujairah vs Yanbu split', unit: '%', manual: true, cadence: 'assessment' },
    ],
  },
  {
    id: 'n2',
    name: 'Chokepoint Transit',
    category: 'physical',
    summary: 'Hormuz, Bab el-Mandeb, Suez — inbound/outbound + dark transits',
    keyMetric: 'Hormuz outbound transits',
    phase: 2,
    manualSources: [
      'Windward AI MIOC dashboard — Hormuz in/out, dark transits (manual)',
      'Windward AI MIOC dashboard — Bab el-Mandeb, Suez crossings (manual, 8-day rolling)',
      'straits.live /status — automated: IMF PortWatch daily counts, AIS dark fleet, stranded vessels',
      'straits.live /api/v1/chokepoints — automated: 5-chokepoint daily comparison',
    ],
    thresholdInfo: [
      'RED: Hormuz PortWatch ≤15 transits/day',
      'RED: Hormuz outbound <30 AND Bab el-Mandeb outbound <5 simultaneously',
      'AMBER: PortWatch ≤30/day',
      'AMBER: Inbound <70% of outbound (tankers refusing to enter)',
      'AMBER: Dark transits >30% of outbound, or AIS dark count >60',
      'AMBER: Stranded vessels >500',
    ],
    series: [
      { key: 'hormuz_portwatch', label: 'Hormuz transits (PortWatch)', unit: '/day', manual: false, cadence: 'daily', source: 'PortWatch' },
      { key: 'hormuz_tanker', label: 'Hormuz tanker transits', unit: '/day', manual: false, cadence: 'daily', source: 'PortWatch' },
      { key: 'hormuz_dark_ais', label: 'Hormuz AIS dark count', unit: 'vessels', manual: false, cadence: 'daily', source: 'straits.live' },
      { key: 'stranded_offshore', label: 'Stranded vessels (offshore)', unit: 'vessels', manual: false, cadence: 'daily', source: 'straits.live' },
      { key: 'bab_portwatch', label: 'Bab el-Mandeb (PortWatch)', unit: '/day', manual: false, cadence: 'daily', source: 'PortWatch' },
      { key: 'bab_tanker', label: 'Bab el-Mandeb tankers', unit: '/day', manual: false, cadence: 'daily', source: 'PortWatch' },
      { key: 'suez_portwatch', label: 'Suez (PortWatch)', unit: '/day', manual: false, cadence: 'daily', source: 'PortWatch' },
      { key: 'suez_tanker', label: 'Suez tankers', unit: '/day', manual: false, cadence: 'daily', source: 'PortWatch' },
      { key: 'cape_portwatch', label: 'Cape of Good Hope (PortWatch)', unit: '/day', manual: false, cadence: 'daily', source: 'PortWatch' },
      { key: 'cape_tanker', label: 'Cape tankers', unit: '/day', manual: false, cadence: 'daily', source: 'PortWatch' },
      { key: 'hormuz_outbound', label: 'Hormuz outbound (Windward)', unit: '/day', manual: true, cadence: 'weekly' },
      { key: 'hormuz_inbound', label: 'Hormuz inbound (Windward)', unit: '/day', manual: true, cadence: 'weekly' },
      { key: 'hormuz_dark', label: 'Hormuz dark (Windward)', unit: '/day', manual: true, cadence: 'weekly' },
      { key: 'bab_outbound', label: 'Bab el-Mandeb out (Windward 8d)', unit: '/8d', manual: true, cadence: 'weekly' },
      { key: 'bab_inbound', label: 'Bab el-Mandeb in (Windward 8d)', unit: '/8d', manual: true, cadence: 'weekly' },
      { key: 'suez_outbound', label: 'Suez out (Windward 8d)', unit: '/8d', manual: true, cadence: 'weekly' },
      { key: 'suez_inbound', label: 'Suez in (Windward 8d)', unit: '/8d', manual: true, cadence: 'weekly' },
    ],
  },
  {
    id: 'n3',
    name: 'Tanker Availability',
    category: 'physical',
    summary: 'Freight rates, spot-period gap, shadow fleet share',
    keyMetric: 'Spot-period gap',
    phase: 2,
    manualSources: [
      'Baltic Exchange (via trade press) — VLCC spot rate TD3C benchmark',
      'Clarksons / shipping press — 12-month time charter rate',
      'KSE / CREA reports (PDF) — shadow fleet carriage share',
    ],
    thresholdInfo: [
      'AMBER: Shadow fleet carriage share outside 23–33% band',
      'No red trigger — needs freight rate data (spot vs period gap)',
    ],
    series: [
      { key: 'vlcc_spot', label: 'VLCC spot rate (TD3C)', unit: '$/day', manual: true, cadence: 'weekly' },
      { key: 'vlcc_period', label: '12-month time charter', unit: '$/day', manual: true, cadence: 'weekly' },
      { key: 'shadow_fleet_share', label: 'Shadow fleet carriage share', unit: '%', manual: true, cadence: 'monthly' },
    ],
  },
  {
    id: 'n4',
    name: 'Storage Buffers',
    category: 'physical',
    summary: 'SPR, Cushing, commercial stocks, product inventories, refinery utilisation',
    keyMetric: 'SPR level vs congressional floor',
    phase: 1,
    manualSources: [
      'EIA Weekly Petroleum Status Report — automated (SPR, Cushing, stocks, utilisation)',
      'Satellite analysts / EIA estimates — Chinese strategic reserves (quarterly)',
      'FEDCom / S&P Global (via trade press) — Fujairah commercial stocks',
    ],
    thresholdInfo: [
      'RED: SPR draw rate >4M bbl/week, or Cushing <18M bbl',
      'AMBER: SPR draw >2.5M/week, or Cushing <22M bbl',
      'AMBER: SPR weeks-to-floor <12 weeks (vs DOE contracted floor ~282M bbl)',
      'Draw rate = rolling average over last 4 weekly readings',
    ],
    series: [
      { key: 'spr_level', label: 'US SPR level', unit: 'K bbl', manual: false, cadence: 'weekly', source: 'EIA', eiaId: 'PET.WCSSTUS1.W' },
      { key: 'cushing', label: 'Cushing OK crude stocks', unit: 'K bbl', manual: false, cadence: 'weekly', source: 'EIA', eiaId: 'PET.W_EPC0_SAX_YCUOK_MBBL.W' },
      { key: 'commercial_crude', label: 'US commercial crude stocks', unit: 'K bbl', manual: false, cadence: 'weekly', source: 'EIA', eiaId: 'PET.WCESTUS1.W' },
      { key: 'gasoline_stocks', label: 'US gasoline inventories', unit: 'K bbl', manual: false, cadence: 'weekly', source: 'EIA', eiaId: 'PET.WGTSTUS1.W' },
      { key: 'distillate_stocks', label: 'US distillate inventories', unit: 'K bbl', manual: false, cadence: 'weekly', source: 'EIA', eiaId: 'PET.WDISTUS1.W' },
      { key: 'refinery_utilisation', label: 'Refinery utilisation', unit: '%', manual: false, cadence: 'weekly', source: 'EIA', eiaId: 'PET.WPULEUS3.W' },
      { key: 'chinese_spr', label: 'Chinese strategic reserves', unit: 'M bbl', manual: true, cadence: 'quarterly' },
      { key: 'fujairah_stocks', label: 'Fujairah commercial stocks', unit: 'M bbl', manual: true, cadence: 'weekly' },
    ],
  },
  {
    id: 'n5',
    name: 'Refining & Products',
    category: 'physical',
    summary: 'WTI-Brent spread, crack spreads, product tightness',
    keyMetric: 'Diesel crack spread',
    phase: 1,
    manualSources: [
      'FRED / EIA — automated (WTI, Brent, yields, crack spreads)',
      'Kpler / IEA — Asian distillate exports (paywalled/blog, monthly)',
      'Reuters / trade press — Chinese product-export quotas',
      'Trade press — Singapore refining margins',
    ],
    thresholdInfo: [
      'RED: Diesel crack spread >$40/bbl',
      'AMBER: Diesel crack >$30/bbl',
      'AMBER: Gasoline crack >$25/bbl',
      'AMBER: WTI-Brent spread >$12/bbl',
    ],
    series: [
      { key: 'wti', label: 'WTI spot price', unit: '$/bbl', manual: false, cadence: 'daily', source: 'FRED', fredId: 'DCOILWTICO' },
      { key: 'brent', label: 'Brent spot price', unit: '$/bbl', manual: false, cadence: 'daily', source: 'FRED', fredId: 'DCOILBRENTEU' },
      { key: 'gasoline_crack', label: 'Gasoline crack spread', unit: '$/bbl', manual: false, cadence: 'daily', source: 'calculated' },
      { key: 'diesel_crack', label: 'Diesel crack spread', unit: '$/bbl', manual: false, cadence: 'daily', source: 'calculated' },
      { key: 'yield_10y', label: '10Y Treasury yield', unit: '%', manual: false, cadence: 'daily', source: 'FRED', fredId: 'DGS10' },
      { key: 'yield_30y', label: '30Y Treasury yield', unit: '%', manual: false, cadence: 'daily', source: 'FRED', fredId: 'DGS30' },
      { key: 'singapore_margin', label: 'Singapore refining margin', unit: '$/bbl', manual: true, cadence: 'weekly' },
    ],
  },
  {
    id: 'n6',
    name: 'Alternative Supply Routes',
    category: 'physical',
    summary: 'US crude exports, Atlantic basin substitution',
    keyMetric: 'US crude exports',
    phase: 1,
    manualSources: [
      'EIA — automated (US crude exports, monthly)',
      'Petrobras quarterly + ANP — Brazil crude exports',
      'Hess quarterly / trade press — Guyana production',
      'Argus (via trade press) — West African differentials',
    ],
    thresholdInfo: [
      'RED: West African differentials >$8/bbl (backup route saturated)',
      'AMBER: West African differentials >$5/bbl',
    ],
    series: [
      { key: 'us_crude_exports', label: 'US crude exports', unit: 'K bbl/d', manual: false, cadence: 'monthly', source: 'EIA', eiaId: 'PET.MCREXUS2.M' },
      { key: 'brazil_exports', label: 'Brazil crude exports', unit: 'M bbl/d', manual: true, cadence: 'quarterly' },
      { key: 'guyana_production', label: 'Guyana production', unit: 'K bbl/d', manual: true, cadence: 'quarterly' },
      { key: 'west_africa_diff', label: 'West African differentials', unit: '$/bbl', manual: true, cadence: 'weekly' },
    ],
  },
  {
    id: 'n7',
    name: 'Insurance & Risk Premium',
    category: 'permission',
    summary: 'War-risk premium, JWC listed areas, reinsurer status',
    keyMetric: 'War-risk insurance multiple',
    phase: 3,
    manualSources: [
      'straits.live /status → insurance — automated (multiple, VLCC premium, withdrawn clubs)',
      'straits.live /api/v1/jwc — automated (JWC listed areas)',
      "Lloyd's List / TradeWinds — war-risk premium quotes (manual detail)",
      'FT / trade press — DFC reinsurer policy status',
      'Trade press — India sovereign reinsurance pool',
    ],
    thresholdInfo: [
      'RED: Insurance multiple ≥20x peacetime, or ≥4 P&I clubs withdrawn',
      'AMBER: Insurance multiple ≥10x, or ≥2 clubs withdrawn',
      'Fallback: manual war-risk band upper >5% = red, >3% = amber',
    ],
    series: [
      { key: 'insurance_multiple', label: 'Insurance multiple (vs peacetime)', unit: 'x', manual: false, cadence: 'weekly', source: 'straits.live' },
      { key: 'vlcc_premium_high', label: 'VLCC premium (high)', unit: '$', manual: false, cadence: 'weekly', source: 'straits.live' },
      { key: 'clubs_withdrawn', label: 'P&I clubs withdrawn', unit: 'count', manual: false, cadence: 'weekly', source: 'straits.live' },
      { key: 'warrisk_band', label: 'War-risk premium band', unit: '% hull', manual: true, cadence: 'weekly' },
      { key: 'jwc_areas', label: 'JWC listed areas', unit: 'text', manual: true, cadence: 'as_changed' },
      { key: 'dfc_status', label: 'DFC reinsurer status', unit: 'text', manual: true, cadence: 'as_changed' },
      { key: 'india_pool', label: 'India sovereign pool status', unit: 'text', manual: true, cadence: 'as_changed' },
    ],
  },
  {
    id: 'n8',
    name: 'Sanctions Architecture',
    category: 'permission',
    summary: 'Price cap, shadow fleet designations, OFAC waivers, carrier posture',
    keyMetric: 'OFAC waiver cadence',
    phase: 2,
    manualSources: [
      'straits.live /status → vesselRisk — automated (high-risk vessel count)',
      'straits.live /status → carrierSuspensions — automated (carriers rerouting)',
      'OFAC announcements / trade press — waiver/revocation cadence',
      'EU Council decisions — price cap level, dynamic mechanism status',
      'UK/EU/US sanction lists (gov sites) — shadow fleet designations',
      'KSE / CREA reports (PDF) — G7-linked carriage share',
    ],
    thresholdInfo: [
      'RED: ≥7 major carriers rerouting',
      'RED: >80 high-risk vessels (OFAC SDN matches)',
      'AMBER: ≥4 carriers rerouting, or >40 high-risk vessels',
      'AMBER: G7-linked carriage share >30%',
    ],
    series: [
      { key: 'vessels_high_risk', label: 'High-risk vessels (OFAC match)', unit: 'count', manual: false, cadence: 'daily', source: 'straits.live' },
      { key: 'carriers_rerouting', label: 'Major carriers rerouting', unit: 'count', manual: false, cadence: 'weekly', source: 'straits.live' },
      { key: 'price_cap', label: 'G7 price cap level', unit: '$/bbl', manual: true, cadence: 'as_changed' },
      { key: 'shadow_designations', label: 'Shadow fleet designations', unit: 'cumulative', manual: true, cadence: 'monthly' },
      { key: 'ofac_waivers', label: 'OFAC waivers issued', unit: 'count', manual: true, cadence: 'monthly' },
      { key: 'g7_carriage_share', label: 'G7-linked carriage share', unit: '%', manual: true, cadence: 'monthly' },
    ],
  },
];

// FRED series needed for crack spread calculations (not stored directly as node series)
const FRED_INPUTS = {
  gasoline_spot: { fredId: 'DGASNYH', label: 'Gasoline spot (NY Harbor)', unit: '$/gal', fallback: null },
  ulsd_spot: { fredId: 'DDFUELNYH', label: 'ULSD spot (NY Harbor)', unit: '$/gal', fallback: 'DHOILNYH' },
};

// Stale thresholds (days) — how old data can be before flagging
const STALE_THRESHOLDS = {
  daily: 5,
  weekly: 14,
  monthly: 45,
  quarterly: 120,
  assessment: 21,
  as_changed: 60,
};

module.exports = { NODES, FRED_INPUTS, STALE_THRESHOLDS };
